#! /bin/bash

# mcbackup
# usage:
#  ./mcbackup <path_to_mcwrapper>

# path to mcwrapper
MCWRAPPER="$1"

# make sure mcwrapper exists:
if [[ ! -e "$MCWRAPPER" ]]; then
	echo "mcwrapper not found! ($MCWRAPPER)"
	exit 1
fi

# make sure that minecraft is running in mcwrapper
sh "$MCWRAPPER" status
STATUS=$?
if [[ $STATUS != 0 ]]; then
	exit $STATUS # pass the exit code on
fi

# read configurations
MINECRAFT_SERVERDIR=`sh "$MCWRAPPER" config serverdir`
BACKUP_DIR="${MINECRAFT_SERVERDIR}/backups"
WORLD_DIR="${MINECRAFT_SERVERDIR}/world"

# set backup name to
#   +%Y%m%d       -- just the datestamp; no time.
#   +%Y%m%d%H%M%S -- full timestamp including hour, minute, second
CURRENT_BACKUP_NAME=`date +%Y%m%d%H%M%S`
CURRENT_BACKUP_PATH="${BACKUP_DIR}/$CURRENT_BACKUP_NAME"

# create backup directory
mkdir -p $CURRENT_BACKUP_PATH

# write the world, stop writing world data, backup, start writing world again.
sh "$MCWRAPPER" save-all
sh "$MCWRAPPER" save-off

cp -R "$WORLD_DIR" "$CURRENT_BACKUP_PATH/"
cp -R "${MINECRAFT_SERVERDIR}/"*.{txt,properties} "$CURRENT_BACKUP_PATH/"

sh "$MCWRAPPER" save-on

# then we symlink the current backup to "latest" in backups directory
if [[ -e "$BACKUP_DIR/latest" ]]; then
	# if the symlink already exists, delete it before creating it.
	rm "$BACKUP_DIR/latest"
fi
ln -s "$CURRENT_BACKUP_PATH" "$BACKUP_DIR/latest"
