#! /bin/bash

# mcbackup
# usage:
#  ./mcbackup <path_to_mcwrapper>

# path to mcwrapper
MCWRAPPER="$1"

# make sure that minecraft is running in mcwrapper
sh "$MCWRAPPER" status
STATUS=$?
if [[ $STATUS != 0 ]]; then
	exit $STATUS # pass the exit code on
fi

# read configurations
MINECRAFT_SERVERPATH=`sh "$MCWRAPPER" config serverpath`


echo "Read server: $MINECRAFT_SERVERPATH"